spring:
  profiles:
    active:
      - cat
      - EN
      - dev
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: YmlProdDBUser
  password: YmlProdPassword
  jdbcurl: YmlProdURL